services:
  deviantart_downloader:
    container_name: deviantart_downloader
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      - CLIENT_ID=${ID}
      - CLIENT_SECRET=${SECRET}
      - USERNAME=${USER}
      - SAVE_DIR=/downloads
      - DB_PATH=/downloads/deviantart.db
      - LOG_PATH=/downloads/downloader.log
      - SLEEP_TIME=2.5
      - MAX_RETRIES=10
      - RATE_LIMIT_SLEEP=120
      - FORCE_RECHECK=false
      - DOWNLOAD_SUBSCRIPTIONS=false
      - DEBUG_MODE=false
      - REDIRECT_URI=http://localhost:8080/callback
      - AUTOTAGGER_URL=http://autotagger-deviantart:5000/evaluate
      - ENABLE_AUTOTAGGER=true
    volumes:
      - ./downloads:/downloads
      - ./temporary:/temporary
  autotagger-deviantart:
      container_name: autotagger-deviantart
      image: ghcr.io/danbooru/autotagger
      depends_on:
        - deviantart_downloader